services:
  node-xau-1:
    build: .
    volumes:
      - ./configs/config-xau-1.yml:/app/config.yml
    ports:
      - "8001:8000"
    command: python node/main.py run -c config.yml

  node-xau-2:
    build: .
    volumes:
      - ./configs/config-xau-2.yml:/app/config.yml
    ports:
      - "8002:8000"
    command: python node/main.py run -c config.yml

  node-xag-1:
    build: .
    volumes:
      - ./configs/config-xag-1.yml:/app/config.yml
    ports:
      - "8003:8000"
    command: python node/main.py run -c config.yml

  node-xag-2:
    build: .
    volumes:
      - ./configs/config-xag-2.yml:/app/config.yml
    ports:
      - "8004:8000"
    command: python node/main.py run -c config.yml
